# Generated by Django 5.2.17 on 2026-09-07 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('publisher', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('feed_url', models.URLField(blank=True, db_index=True, default='', max_length=1000)),
                ('website_url', models.URLField(blank=True, default='', max_length=1000)),
                ('rating', models.FloatField(blank=True, help_text='Orta reytinq xalı (məs: 4.8)', null=True)),
                ('rating_count', models.IntegerField(default=0, help_text='Səs verənlərin sayı')),
                ('frequency', models.CharField(blank=True, default='', help_text='Yayımlanma tezliyi: daily, weekly və s.', max_length=100)),
                ('language', models.CharField(blank=True, default='en', max_length=20)),
                ('apple_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('spotify_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='podcasts', to='podcasts.category')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(help_text='RSS feed daxilindəki unikal identifikator', max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('audio_url', models.URLField(max_length=1500)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration', models.CharField(blank=True, default='', help_text='Müddət formatı (məs: 00:45:30)', max_length=50)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcast')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChartRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('podchaser', 'Podchaser')], db_index=True, max_length=30)),
                ('country', models.CharField(db_index=True, default='us', max_length=10)),
                ('category', models.CharField(db_index=True, default='top', max_length=100)),
                ('rank', models.PositiveIntegerField(help_text='Reytinqdəki yeri (1, 2, 3...)')),
                ('date', models.DateField(db_index=True, help_text='Reytinqin qeydə alındığı tarix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_rankings', to='podcasts.podcast')),
            ],
            options={
                'verbose_name': 'Chart Ranking',
                'verbose_name_plural': 'Chart Rankings',
                'ordering': ['date', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['title'], name='podcasts_po_title_b6422d_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['publisher'], name='podcasts_po_publish_c29306_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['podcast', '-published_at'], name='podcasts_ep_podcast_7dabdb_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['guid'], name='podcasts_ep_guid_b8bf34_idx'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('podcast', 'guid'), name='unique_podcast_episode_guid'),
        ),
        migrations.AddIndex(
            model_name='chartranking',
            index=models.Index(fields=['country', 'category', 'date', 'source'], name='idx_chart_filter'),
        ),
        migrations.AddIndex(
            model_name='chartranking',
            index=models.Index(fields=['date', 'source', 'rank'], name='idx_chart_date_rank'),
        ),
        migrations.AddConstraint(
            model_name='chartranking',
            constraint=models.UniqueConstraint(fields=('source', 'country', 'category', 'date', 'rank'), name='unique_chart_daily_rank'),
        ),
        migrations.AddConstraint(
            model_name='chartranking',
            constraint=models.UniqueConstraint(fields=('source', 'country', 'category', 'date', 'podcast'), name='unique_chart_daily_podcast'),
        ),
    ]
