# Generated by Django 5.2.17 on 2026-09-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('apple', 'Apple Podcasts'), ('podchaser', 'Podchaser'), ('youtube', 'YouTube Podcasts'), ('amazon', 'Amazon Music')], db_index=True, help_text='Reytinqin aid olduğu platforma (məs: spotify, apple)', max_length=30)),
                ('rating', models.FloatField(help_text='Platformanın orta balı (məs: 4.74)')),
                ('rating_count', models.IntegerField(default=0, help_text='Səs verənlərin sayı (məs: 117106)')),
                ('url', models.URLField(blank=True, default='', help_text='Platformadakı podkast profil linki', max_length=1000)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Reytinqin ən son sinxronizasiya vaxtı')),
                ('podcast', models.ForeignKey(help_text='Aid olduğu podkast', on_delete=django.db.models.deletion.CASCADE, related_name='platform_ratings', to='podcasts.podcast')),
            ],
            options={
                'verbose_name': 'Podcast Rating',
                'verbose_name_plural': 'Podcast Ratings',
                'ordering': ['-rating_count', '-rating'],
                'indexes': [models.Index(fields=['source', 'rating'], name='podcasts_po_source_0ea35c_idx'), models.Index(fields=['podcast', 'source'], name='podcasts_po_podcast_bc03d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('podcast', 'source'), name='unique_podcast_platform_rating')],
            },
        ),
    ]
