# Generated by Django 5.2.17 on 2026-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcastrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartCategory',
            fields=[
                ('slug', models.SlugField(help_text='Chart kateqoriyasının unikal identifikatoru (məs: top-podcasts, trending, comedy)', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Oxunaqlı ad (məs: Top Podcasts, Trending, Comedy Chart)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Chart kateqoriyası haqqında qısa izah')),
                ('platform', models.CharField(default='all', help_text="Dəstəkləyən platforma ('all', 'spotify', 'apple')", max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Bu chart növü üzrə məlumat toplansınmı?')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='UI-da göstərilmə sırası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chart Kateqoriyası',
                'verbose_name_plural': 'Chart Kateqoriyaları (Chart Categories)',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 ölkə kodu (məs: us, az, gb)', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ölkənin rəsmi adı (məs: Azerbaijan, United States)', max_length=100)),
                ('supports_apple', models.BooleanField(default=True, help_text='Apple Podcasts chart dəstəkləyirmi?')),
                ('supports_spotify', models.BooleanField(default=False, help_text='Spotify Charts dəstəkləyirmi?')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Bu ölkə üçün gündəlik məlumat çəkimi aktivdirmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ölkə',
                'verbose_name_plural': 'Ölkələr (Countries)',
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='PodcastCategory',
        ),
        migrations.AlterModelOptions(
            name='podcastcategory',
            options={'ordering': ['name'], 'verbose_name': 'Podkast Kateqoriyası', 'verbose_name_plural': 'Podkast Kateqoriyaları (Podcast Categories)'},
        ),
        migrations.AlterModelTable(
            name='podcastcategory',
            table='podcasts_category',
        ),
    ]
