# Generated by Django 5.2.17 on 2026-09-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_chartcategory_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartranking',
            name='category',
            field=models.ForeignKey(db_column='category', help_text='Reytinq lövhəsi / kateqoriyası', on_delete=django.db.models.deletion.CASCADE, related_name='chart_rankings', to='podcasts.chartcategory'),
        ),
        migrations.AlterField(
            model_name='chartranking',
            name='country',
            field=models.ForeignKey(db_column='country', help_text='Reytinqin aid olduğu ölkə', on_delete=django.db.models.deletion.CASCADE, related_name='chart_rankings', to='podcasts.country'),
        ),
    ]
