# Generated by Django 5.2.17 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


def partition_chartranking_table(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        # SQLite və digər mühitlər üçün sadəcə sütunu əlavə edirik
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE podcasts_chartranking ADD COLUMN episode_id bigint REFERENCES podcasts_episode(id);")
        return

    with schema_editor.connection.cursor() as cursor:
        # 1. Mövcud məlumatları müvəqqəti cədvələ ehtiyat kopyalayırıq
        cursor.execute("""
            CREATE TABLE podcasts_chartranking_backup AS 
            SELECT * FROM podcasts_chartranking;
        """)

        # 2. Köhnə partisyasız cədvəli silirik (bütün məhdudiyyət və indeks adları azad olur)
        cursor.execute("""
            DROP TABLE podcasts_chartranking CASCADE;
        """)

        # 3. RANGE (date) üzrə bölmələrə (partition) ayrılmış yeni cədvəli yaradırıq
        cursor.execute("""
            CREATE TABLE podcasts_chartranking (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                source character varying(30) NOT NULL,
                country character varying(5) NOT NULL REFERENCES podcasts_country(code) DEFERRABLE INITIALLY DEFERRED,
                category character varying(100) NOT NULL REFERENCES podcasts_chartcategory(slug) DEFERRABLE INITIALLY DEFERRED,
                rank integer NOT NULL CHECK (rank >= 0),
                date date NOT NULL,
                created_at timestamp with time zone NOT NULL,
                podcast_id bigint NOT NULL REFERENCES podcasts_podcast(id) DEFERRABLE INITIALLY DEFERRED,
                episode_id bigint REFERENCES podcasts_episode(id) DEFERRABLE INITIALLY DEFERRED,
                PRIMARY KEY (id, date),
                CONSTRAINT unique_chart_daily_rank UNIQUE (source, country, category, date, rank),
                CONSTRAINT unique_chart_daily_podcast UNIQUE (source, country, category, date, podcast_id)
            ) PARTITION BY RANGE (date);
        """)

        # 4. İllik partisyaları və standart DEFAULT partisyasını yaradırıq
        cursor.execute("""
            CREATE TABLE podcasts_chartranking_2025 PARTITION OF podcasts_chartranking
                FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

            CREATE TABLE podcasts_chartranking_2026 PARTITION OF podcasts_chartranking
                FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

            CREATE TABLE podcasts_chartranking_2027 PARTITION OF podcasts_chartranking
                FOR VALUES FROM ('2027-01-01') TO ('2028-01-01');

            CREATE TABLE podcasts_chartranking_default PARTITION OF podcasts_chartranking
                DEFAULT;
        """)

        # 5. Yüksək performanslı indeksləri partisyalı cədvələ bağlayırıq
        cursor.execute("""
            CREATE INDEX idx_chart_filter ON podcasts_chartranking (country, category, date, source);
            CREATE INDEX idx_chart_date_rank ON podcasts_chartranking (date, source, rank);
            CREATE INDEX idx_chart_episode_id ON podcasts_chartranking (episode_id);
            CREATE INDEX idx_chart_podcast_id ON podcasts_chartranking (podcast_id);
        """)

        # 6. Məlumatları geri bərpa edirik
        cursor.execute("""
            INSERT INTO podcasts_chartranking (id, source, country, category, rank, date, created_at, podcast_id)
            SELECT id, source, country, category, rank, date, created_at, podcast_id
            FROM podcasts_chartranking_backup;
        """)

        # 7. Müvəqqəti cədvəli silirik və triggerləri dərhal icra edirik
        cursor.execute("""
            DROP TABLE podcasts_chartranking_backup;
            SET CONSTRAINTS ALL IMMEDIATE;
            SELECT setval(pg_get_serial_sequence('podcasts_chartranking', 'id'), COALESCE((SELECT MAX(id) FROM podcasts_chartranking), 1));
        """)


def reverse_partition_chartranking_table(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE podcasts_chartranking_backup AS 
            SELECT * FROM podcasts_chartranking;

            DROP TABLE podcasts_chartranking CASCADE;

            CREATE TABLE podcasts_chartranking (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source character varying(30) NOT NULL,
                country character varying(5) NOT NULL REFERENCES podcasts_country(code) DEFERRABLE INITIALLY DEFERRED,
                category character varying(100) NOT NULL REFERENCES podcasts_chartcategory(slug) DEFERRABLE INITIALLY DEFERRED,
                rank integer NOT NULL CHECK (rank >= 0),
                date date NOT NULL,
                created_at timestamp with time zone NOT NULL,
                podcast_id bigint NOT NULL REFERENCES podcasts_podcast(id) DEFERRABLE INITIALLY DEFERRED,
                episode_id bigint REFERENCES podcasts_episode(id) DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT unique_chart_daily_rank UNIQUE (source, country, category, date, rank),
                CONSTRAINT unique_chart_daily_podcast UNIQUE (source, country, category, date, podcast_id)
            );

            CREATE INDEX idx_chart_filter ON podcasts_chartranking (country, category, date, source);
            CREATE INDEX idx_chart_date_rank ON podcasts_chartranking (date, source, rank);
            CREATE INDEX idx_chart_episode_id ON podcasts_chartranking (episode_id);
            CREATE INDEX idx_chart_podcast_id ON podcasts_chartranking (podcast_id);

            INSERT INTO podcasts_chartranking (id, source, country, category, rank, date, created_at, podcast_id, episode_id)
            SELECT id, source, country, category, rank, date, created_at, podcast_id, episode_id
            FROM podcasts_chartranking_backup;

            DROP TABLE podcasts_chartranking_backup;
            SET CONSTRAINTS ALL IMMEDIATE;
            SELECT setval(pg_get_serial_sequence('podcasts_chartranking', 'id'), COALESCE((SELECT MAX(id) FROM podcasts_chartranking), 1));
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_alter_chartranking_category_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='chartranking',
                    name='episode',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Top epizod reytinqləri üçün fərdi epizod bağı',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chart_rankings',
                        to='podcasts.episode'
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    code=partition_chartranking_table,
                    reverse_code=reverse_partition_chartranking_table,
                ),
            ],
        ),
    ]
