# Generated by Django 5.2.17 on 2026-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_chartranking_partitioning_and_episode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chartranking',
            name='unique_chart_daily_podcast',
        ),
        migrations.AddConstraint(
            model_name='chartranking',
            constraint=models.UniqueConstraint(condition=models.Q(('episode__isnull', True)), fields=('source', 'country', 'category', 'date', 'podcast'), name='unique_chart_daily_podcast'),
        ),
        migrations.AddConstraint(
            model_name='chartranking',
            constraint=models.UniqueConstraint(condition=models.Q(('episode__isnull', False)), fields=('source', 'country', 'category', 'date', 'episode'), name='unique_chart_daily_episode'),
        ),
    ]
