# Generated by Django 5.2.17 on 2026-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_remove_chartranking_unique_chart_daily_podcast_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chartranking',
            index=models.Index(fields=['category'], name='idx_chart_category'),
        ),
    ]
