# Generated by Django 5.2.17 on 2026-09-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_chartranking_idx_chart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartcategory',
            name='apple_genre_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Apple Podcasts rəsmi janr/kateqoriya ID-si (məs: 1303, 1488, 1482)', null=True),
        ),
    ]
