# Generated by Django 5.2.17 on 2026-09-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_chartcategory_apple_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Ana kateqoriya (məs: 'investing' üçün 'business')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='podcasts.chartcategory'),
        ),
        migrations.AddField(
            model_name='podcastcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Ana kateqoriya', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='podcasts.podcastcategory'),
        ),
    ]
