# Generated by Django 5.2.17 on 2026-09-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_chartcategory_parent_podcastcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartcategory',
            name='platform',
            field=models.CharField(choices=[('all', 'All Platforms'), ('spotify', 'Spotify'), ('apple', 'Apple Podcasts')], default='all', help_text="Dəstəkləyən platforma ('all', 'spotify', 'apple')", max_length=30),
        ),
    ]
